### ISSUE TITLE
Support `(token:1.3)` weighting syntax in prompts

### ISSUE THREAD

**Issue by irgolic** [irgolic/stable-diffusion-server#19]
Wherein `1.3` represents the relative weighting of `token`'s latent vector compared to those of the other tokens.

Ideally this is implemented in a way that allows use of any custom tokenizer (e.g., one that supports the `((token))` syntax, wherein each `()` pair increases the latent vector magnitude by 1.1). Perhaps that's not possible, and the solution is to replace [`stable_diffusion_mega`](https://github.com/huggingface/diffusers/tree/main/examples/community#stable-diffusion-mega) with [`lpw_stable_diffusion`](https://github.com/huggingface/diffusers/tree/main/examples/community#long-prompt-weighting-stable-diffusion).

**Comment by MicahZoltu** [comment]
Even better (perhaps longer term) would be to move the entire parsing/tokenizing phase to the client.  This is under the assumption that the parsing/tokenizing isn't done with an AI in any way and is just a traditional parser/tokenizer, which can be run in a browser without any problem.

**Comment by irgolic** [comment]
Thanks for contributing 🙏 

I was thinking about this too when determining the interface for prompt, but it seems like pipelines on huggingface tend to take a prompt in as a single string. You can pass a list of strings, but that means generate multiple images, one for each list element.

https://github.com/huggingface/diffusers/blob/main/examples/community/lpw_stable_diffusion_onnx.py#L39
This is where the `()` syntax is parsed in `lpw_stable_diffusion`. If this step were abstracted for the client to compute, the prompt interface would have to be `prompt: list[tuple[str, float]]`, mapping tokens to their relative weightings.

[Here's a short primer on tokenization.](https://huggingface.co/docs/transformers/tokenizer_summary) The methods get more complex, and require dependencies on the server (e.g., ftfy). From what I've seen, multi-modal models like to rely on [CLIP](https://huggingface.co/docs/transformers/v4.23.1/en/model_doc/clip#transformers.CLIPTokenizer), a tokenizer that embeds prompts into the same space as images. CLIP can take either a `prompt: str` or `prompt: list[str]` (pre-tokenized) input.

With that in mind, I'm leaning toward keeping prompts as strings for the foreseeable future.
